### ISSUE TITLE
Use of `all.equal()` in `simple_ensemble()` sometimes throws an error

### ISSUE THREAD

**Issue by lshandross** [hubverse-org/hubEnsembles#134]
When calling `simple_ensemble()` with a custom function, R threw the error: "Error: Cannot unclass an external pointer." 

Reproducible example taken from the [hubEnsembles manuscript](https://github.com/hubverse-org/hubEnsemblesManuscript/blob/f70837b5f0816cc5e6ff680a9ad0a0a37feb9b7a/analysis/paper/hubEnsembles_manuscript.qmd#L749) is as follows:

```r
geometric_mean <- function(x) {
    n <- length(x)
    return(prod(x)^(1 / n))
  }
geometric_mean_ens <- hubExamples::forecast_outputs |>
    dplyr::filter(output_type != "sample") |>
    hubEnsembles::simple_ensemble(
      agg_fun = geometric_mean,
      model_id = "simple-ensemble-geometric"
    )
```

Investigation into the error reveals it originated from the usage of `all.equal()` within `simple_ensemble()`.

**Comment by zkamvar** [comment]
This error is unusual. 

I found a post from 2012 that mentions it, but it's not very informative: https://hypatia.math.ethz.ch/pipermail/r-devel/2012-September/064809.html

That being said, there is discussion in https://github.com/ropensci/hunspell/issues/31 that I have not yet parsed, which may or may not contain a trace of this.

@lshandross, did you happen to record a `traceback()` when you got the error?
Can you reproduce it? 
How often would the error occur?

**Comment by zkamvar** [comment]
The reason I ask is because you may continue to see this since the `all.equal` method for `function` uses `identical()`. I _suspect_ that the error is coming from `all.equal.environment()` (given [the discussion from 2012](https://hypatia.math.ethz.ch/pipermail/r-devel/2012-September/064809.html)), but if it's coming from the call to `identical()`, you may continue to run into this problem. 

```f
function (target, current, check.environment = TRUE, ...) 
{
    msg <- all.equal.language(target, current, ...)
    if (check.environment) {
        ee <- identical(environment(target), environment(current), 
            ignore.environment = FALSE)
        if (!ee) 
            ee <- all.equal.environment(environment(target), 
                environment(current), ...)
        if (isTRUE(msg)) 
            ee
        else c(msg, if (!isTRUE(ee)) ee)
    }
    else msg
}
```

**Comment by lshandross** [comment]
I can go back and try to reproduce it, but I'm fairly certain that the error was coming from the `all.equal()` call based on the traceback results and because the error message disappeared when I used `identical()` instead

**Comment by zkamvar** [comment]
Do you still have the traceback() results? 

It would be good to know if the traceback was pointing to `all.equal.environment()` for confirmation.

**Comment by lshandross** [comment]
Looks like it was pointing to `all.equal.environment()`:

```
Error in unclass(current) : cannot unclass an external pointer
12.
all.equal.list(target, current, ...)
11.
all.equal.default(target[[i]], current[[i]], check.attributes = check.attributes,
use.names = use.names, ...)
10.
all.equal(target[[i]], current[[i]], check.attributes = check.attributes,
use.names = use.names, ...)
9.
all.equal.list(target, current, ...)
8.
all.equal.default(target[[i]], current[[i]], check.attributes = check.attributes,
use.names = use.names, ...)
7.
all.equal(target[[i]], current[[i]], check.attributes = check.attributes,
use.names = use.names, ...)
6.
all.equal.list(Lt, Lc, ...)
5.
all.equal.environment(environment(target), environment(current),
...)
4.
all.equal.function(agg_fun, matrixStats::weightedMedian)
3.
all.equal(agg_fun, matrixStats::weightedMedian)
2.
isTRUE(all.equal(agg_fun, matrixStats::weightedMedian)) at simple_ensemble.R#97
1.
hubEnsembles::simple_ensemble(dplyr::filter(hubExamples::forecast_outputs,
output_type != "sample"), agg_fun = geometric_mean, model_id = "simple-ensemble-geometric")
```

**Comment by zkamvar** [comment]
Thank you!
